// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "ZcmCameraBaslerImagePresentation.h"

static int __ZcmCameraBaslerImagePresentation_hash_computed = 0;
static uint64_t __ZcmCameraBaslerImagePresentation_hash;

uint64_t __ZcmCameraBaslerImagePresentation_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmCameraBaslerImagePresentation_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmCameraBaslerImagePresentation_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xd9af91e2fd9d4b64LL
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __byte_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmCameraBaslerImagePresentation_get_hash(void)
{
    if (!__ZcmCameraBaslerImagePresentation_hash_computed) {
        __ZcmCameraBaslerImagePresentation_hash = (int64_t)__ZcmCameraBaslerImagePresentation_hash_recursive(NULL);
        __ZcmCameraBaslerImagePresentation_hash_computed = 1;
    }

    return __ZcmCameraBaslerImagePresentation_hash;
}

int __ZcmCameraBaslerImagePresentation_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCameraBaslerImagePresentation* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].bytes_per_line), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].format), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].data_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, p[element].data, p[element].data_size);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmCameraBaslerImagePresentation_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCameraBaslerImagePresentation* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmCameraBaslerImagePresentation_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmCameraBaslerImagePresentation_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmCameraBaslerImagePresentation_encoded_array_size(const ZcmCameraBaslerImagePresentation* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __int32_t_encoded_array_size(&(p[element].width), 1);

        size += __int32_t_encoded_array_size(&(p[element].height), 1);

        size += __int32_t_encoded_array_size(&(p[element].bytes_per_line), 1);

        size += __string_encoded_array_size(&(p[element].format), 1);

        size += __int32_t_encoded_array_size(&(p[element].data_size), 1);

        size += __byte_encoded_array_size(p[element].data, p[element].data_size);

    }
    return size;
}

uint32_t ZcmCameraBaslerImagePresentation_encoded_size(const ZcmCameraBaslerImagePresentation* p)
{
    return 8 + __ZcmCameraBaslerImagePresentation_encoded_array_size(p, 1);
}

uint32_t ZcmCameraBaslerImagePresentation_struct_size(void)
{
    return sizeof(ZcmCameraBaslerImagePresentation);
}

uint32_t ZcmCameraBaslerImagePresentation_num_fields(void)
{
    return 6;
}

int ZcmCameraBaslerImagePresentation_get_field(const ZcmCameraBaslerImagePresentation* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmCameraBaslerImagePresentation_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "width";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->width;
            return 0;
        }
        
        case 1: {
            f->name = "height";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->height;
            return 0;
        }
        
        case 2: {
            f->name = "bytes_per_line";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->bytes_per_line;
            return 0;
        }
        
        case 3: {
            f->name = "format";
            f->type = ZCM_FIELD_STRING;
            f->typestr = "string";
            f->num_dim = 0;
            f->data = (void*) &p->format;
            return 0;
        }
        
        case 4: {
            f->name = "data_size";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->data_size;
            return 0;
        }
        
        case 5: {
            f->name = "data";
            f->type = ZCM_FIELD_BYTE;
            f->typestr = "byte";
            f->num_dim = 1;
            f->dim_size[0] = p->data_size;
            f->dim_is_variable[0] = 1;
            f->data = (void*) &p->data;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmCameraBaslerImagePresentation_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmCameraBaslerImagePresentation_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmCameraBaslerImagePresentation_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmCameraBaslerImagePresentation_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmCameraBaslerImagePresentation_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmCameraBaslerImagePresentation_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmCameraBaslerImagePresentation_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmCameraBaslerImagePresentation_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmCameraBaslerImagePresentation_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmCameraBaslerImagePresentation_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCameraBaslerImagePresentation* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].bytes_per_line), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].format), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].data_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].data = (uint8_t*) zcm_malloc(sizeof(uint8_t) * p[element].data_size);
        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, p[element].data, p[element].data_size);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmCameraBaslerImagePresentation_decode_array_cleanup(ZcmCameraBaslerImagePresentation* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __int32_t_decode_array_cleanup(&(p[element].width), 1);

        __int32_t_decode_array_cleanup(&(p[element].height), 1);

        __int32_t_decode_array_cleanup(&(p[element].bytes_per_line), 1);

        __string_decode_array_cleanup(&(p[element].format), 1);

        __int32_t_decode_array_cleanup(&(p[element].data_size), 1);

        __byte_decode_array_cleanup(p[element].data, p[element].data_size);
        if (p[element].data) free(p[element].data);

    }
    return 0;
}

int ZcmCameraBaslerImagePresentation_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCameraBaslerImagePresentation* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmCameraBaslerImagePresentation_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmCameraBaslerImagePresentation_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmCameraBaslerImagePresentation_decode_cleanup(ZcmCameraBaslerImagePresentation* p)
{
    return __ZcmCameraBaslerImagePresentation_decode_array_cleanup(p, 1);
}

uint32_t __ZcmCameraBaslerImagePresentation_clone_array(const ZcmCameraBaslerImagePresentation* p, ZcmCameraBaslerImagePresentation* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __int32_t_clone_array(&(p[element].width), &(q[element].width), 1);

        n += __int32_t_clone_array(&(p[element].height), &(q[element].height), 1);

        n += __int32_t_clone_array(&(p[element].bytes_per_line), &(q[element].bytes_per_line), 1);

        n += __string_clone_array(&(p[element].format), &(q[element].format), 1);

        n += __int32_t_clone_array(&(p[element].data_size), &(q[element].data_size), 1);

        q[element].data = (uint8_t*) zcm_malloc(sizeof(uint8_t) * q[element].data_size);
        n += __byte_clone_array(p[element].data, q[element].data, p[element].data_size);

    }
    return n;
}

ZcmCameraBaslerImagePresentation* ZcmCameraBaslerImagePresentation_copy(const ZcmCameraBaslerImagePresentation* p)
{
    ZcmCameraBaslerImagePresentation* q = (ZcmCameraBaslerImagePresentation*) malloc(sizeof(ZcmCameraBaslerImagePresentation));
    __ZcmCameraBaslerImagePresentation_clone_array(p, q, 1);
    return q;
}

void ZcmCameraBaslerImagePresentation_destroy(ZcmCameraBaslerImagePresentation* p)
{
    __ZcmCameraBaslerImagePresentation_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmCameraBaslerImagePresentation_publish(zcm_t* zcm, const char* channel, const ZcmCameraBaslerImagePresentation* p)
{
      uint32_t max_data_size = ZcmCameraBaslerImagePresentation_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmCameraBaslerImagePresentation_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmCameraBaslerImagePresentation_subscription_t {
    ZcmCameraBaslerImagePresentation_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmCameraBaslerImagePresentation_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmCameraBaslerImagePresentation p;
    memset(&p, 0, sizeof(ZcmCameraBaslerImagePresentation));
    status = ZcmCameraBaslerImagePresentation_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding ZcmCameraBaslerImagePresentation!!!\n", status);
        #endif
        return;
    }

    ZcmCameraBaslerImagePresentation_subscription_t* h = (ZcmCameraBaslerImagePresentation_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmCameraBaslerImagePresentation_decode_cleanup (&p);
}

ZcmCameraBaslerImagePresentation_subscription_t* ZcmCameraBaslerImagePresentation_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmCameraBaslerImagePresentation_handler_t f, void* userdata)
{
    ZcmCameraBaslerImagePresentation_subscription_t* n = (ZcmCameraBaslerImagePresentation_subscription_t*)
                       malloc(sizeof(ZcmCameraBaslerImagePresentation_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmCameraBaslerImagePresentation_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg ZcmCameraBaslerImagePresentation ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int ZcmCameraBaslerImagePresentation_unsubscribe(zcm_t* zcm, ZcmCameraBaslerImagePresentation_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe ZcmCameraBaslerImagePresentation_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

