// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _ZcmCameraBaslerInformation_h
#define _ZcmCameraBaslerInformation_h

#ifdef __cplusplus
extern "C" {
#endif

#include "ZcmCameraCalibratingParams.h"
/**
 * =======================================================================================
 * @struct ZcmCameraBaslerInformation
 * @brief  Информация о камере-передатчике.
 *
 *
 * @var   ZcmCameraBaslerInformation::user_defined_name
 * @brief Из PylonIpConfigurator камере может быть присвоено имя, оно и передается.
 *
 * @var   ZcmCameraBaslerInformation::location
 * @brief Передается информация о местонахождении камеры.
 * Предполагаются FrontLeft, FrontRight, RearLeft, RearRight.
 *
 */
typedef struct _ZcmCameraBaslerInformation ZcmCameraBaslerInformation;
struct _ZcmCameraBaslerInformation
{
    char*      serial_number;
    char*      user_defined_name;
    ZcmCameraCalibratingParams calibrating_params;
};

/**
 * Create a deep copy of a ZcmCameraBaslerInformation.
 * When no longer needed, destroy it with ZcmCameraBaslerInformation_destroy()
 */
ZcmCameraBaslerInformation* ZcmCameraBaslerInformation_copy(const ZcmCameraBaslerInformation* to_copy);

/**
 * Destroy an instance of ZcmCameraBaslerInformation created by ZcmCameraBaslerInformation_copy()
 */
void ZcmCameraBaslerInformation_destroy(ZcmCameraBaslerInformation* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _ZcmCameraBaslerInformation_subscription_t ZcmCameraBaslerInformation_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * ZcmCameraBaslerInformation is received.
 */
typedef void(*ZcmCameraBaslerInformation_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const ZcmCameraBaslerInformation* msg, void* userdata);

/**
 * Publish a message of type ZcmCameraBaslerInformation using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int ZcmCameraBaslerInformation_publish(zcm_t* zcm, const char* channel, const ZcmCameraBaslerInformation* msg);

/**
 * Subscribe to messages of type ZcmCameraBaslerInformation using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to ZcmCameraBaslerInformation_unsubscribe.
 */
ZcmCameraBaslerInformation_subscription_t* ZcmCameraBaslerInformation_subscribe(zcm_t* zcm, const char* channel, ZcmCameraBaslerInformation_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by ZcmCameraBaslerInformation_subscribe()
 */
int ZcmCameraBaslerInformation_unsubscribe(zcm_t* zcm, ZcmCameraBaslerInformation_subscription_t* hid);
/**
 * Encode a message of type ZcmCameraBaslerInformation into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to ZcmCameraBaslerInformation_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int ZcmCameraBaslerInformation_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCameraBaslerInformation* p);

/**
 * Decode a message of type ZcmCameraBaslerInformation from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with ZcmCameraBaslerInformation_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int ZcmCameraBaslerInformation_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCameraBaslerInformation* msg);

/**
 * Release resources allocated by ZcmCameraBaslerInformation_decode()
 * @return 0
 */
int ZcmCameraBaslerInformation_decode_cleanup(ZcmCameraBaslerInformation* p);

/**
 * Check how many bytes are required to encode a message of type ZcmCameraBaslerInformation
 */
uint32_t ZcmCameraBaslerInformation_encoded_size(const ZcmCameraBaslerInformation* p);
uint32_t ZcmCameraBaslerInformation_struct_size(void);
uint32_t ZcmCameraBaslerInformation_num_fields(void);
int      ZcmCameraBaslerInformation_get_field(const ZcmCameraBaslerInformation* p, uint32_t i, zcm_field_t* f);
const zcm_type_info_t* ZcmCameraBaslerInformation_get_type_info(void);

// ZCM support functions. Users should not call these
int64_t  __ZcmCameraBaslerInformation_get_hash(void);
uint64_t __ZcmCameraBaslerInformation_hash_recursive(const __zcm_hash_ptr* p);
int      __ZcmCameraBaslerInformation_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCameraBaslerInformation* p, uint32_t elements);
int      __ZcmCameraBaslerInformation_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCameraBaslerInformation* p, uint32_t elements);
int      __ZcmCameraBaslerInformation_decode_array_cleanup(ZcmCameraBaslerInformation* p, uint32_t elements);
uint32_t __ZcmCameraBaslerInformation_encoded_array_size(const ZcmCameraBaslerInformation* p, uint32_t elements);
uint32_t __ZcmCameraBaslerInformation_clone_array(const ZcmCameraBaslerInformation* p, ZcmCameraBaslerInformation* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
