// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "ZcmCameraBaslerInformation.h"

static int __ZcmCameraBaslerInformation_hash_computed = 0;
static uint64_t __ZcmCameraBaslerInformation_hash;

uint64_t __ZcmCameraBaslerInformation_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmCameraBaslerInformation_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmCameraBaslerInformation_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x665c65ab7d017db6LL
         + __string_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __ZcmCameraCalibratingParams_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmCameraBaslerInformation_get_hash(void)
{
    if (!__ZcmCameraBaslerInformation_hash_computed) {
        __ZcmCameraBaslerInformation_hash = (int64_t)__ZcmCameraBaslerInformation_hash_recursive(NULL);
        __ZcmCameraBaslerInformation_hash_computed = 1;
    }

    return __ZcmCameraBaslerInformation_hash;
}

int __ZcmCameraBaslerInformation_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCameraBaslerInformation* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].serial_number), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].user_defined_name), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmCameraCalibratingParams_encode_array(buf, offset + pos, maxlen - pos, &(p[element].calibrating_params), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmCameraBaslerInformation_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCameraBaslerInformation* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmCameraBaslerInformation_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmCameraBaslerInformation_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmCameraBaslerInformation_encoded_array_size(const ZcmCameraBaslerInformation* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __string_encoded_array_size(&(p[element].serial_number), 1);

        size += __string_encoded_array_size(&(p[element].user_defined_name), 1);

        size += __ZcmCameraCalibratingParams_encoded_array_size(&(p[element].calibrating_params), 1);

    }
    return size;
}

uint32_t ZcmCameraBaslerInformation_encoded_size(const ZcmCameraBaslerInformation* p)
{
    return 8 + __ZcmCameraBaslerInformation_encoded_array_size(p, 1);
}

uint32_t ZcmCameraBaslerInformation_struct_size(void)
{
    return sizeof(ZcmCameraBaslerInformation);
}

uint32_t ZcmCameraBaslerInformation_num_fields(void)
{
    return 3;
}

int ZcmCameraBaslerInformation_get_field(const ZcmCameraBaslerInformation* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmCameraBaslerInformation_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "serial_number";
            f->type = ZCM_FIELD_STRING;
            f->typestr = "string";
            f->num_dim = 0;
            f->data = (void*) &p->serial_number;
            return 0;
        }
        
        case 1: {
            f->name = "user_defined_name";
            f->type = ZCM_FIELD_STRING;
            f->typestr = "string";
            f->num_dim = 0;
            f->data = (void*) &p->user_defined_name;
            return 0;
        }
        
        case 2: {
            /* ZcmCameraCalibratingParams */
            f->name = "calibrating_params";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmCameraCalibratingParams";
            f->num_dim = 0;
            f->data = (void*) &p->calibrating_params;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmCameraBaslerInformation_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmCameraBaslerInformation_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmCameraBaslerInformation_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmCameraBaslerInformation_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmCameraBaslerInformation_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmCameraBaslerInformation_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmCameraBaslerInformation_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmCameraBaslerInformation_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmCameraBaslerInformation_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmCameraBaslerInformation_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCameraBaslerInformation* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].serial_number), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].user_defined_name), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmCameraCalibratingParams_decode_array(buf, offset + pos, maxlen - pos, &(p[element].calibrating_params), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmCameraBaslerInformation_decode_array_cleanup(ZcmCameraBaslerInformation* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __string_decode_array_cleanup(&(p[element].serial_number), 1);

        __string_decode_array_cleanup(&(p[element].user_defined_name), 1);

        __ZcmCameraCalibratingParams_decode_array_cleanup(&(p[element].calibrating_params), 1);

    }
    return 0;
}

int ZcmCameraBaslerInformation_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCameraBaslerInformation* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmCameraBaslerInformation_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmCameraBaslerInformation_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmCameraBaslerInformation_decode_cleanup(ZcmCameraBaslerInformation* p)
{
    return __ZcmCameraBaslerInformation_decode_array_cleanup(p, 1);
}

uint32_t __ZcmCameraBaslerInformation_clone_array(const ZcmCameraBaslerInformation* p, ZcmCameraBaslerInformation* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __string_clone_array(&(p[element].serial_number), &(q[element].serial_number), 1);

        n += __string_clone_array(&(p[element].user_defined_name), &(q[element].user_defined_name), 1);

        n += __ZcmCameraCalibratingParams_clone_array(&(p[element].calibrating_params), &(q[element].calibrating_params), 1);

    }
    return n;
}

ZcmCameraBaslerInformation* ZcmCameraBaslerInformation_copy(const ZcmCameraBaslerInformation* p)
{
    ZcmCameraBaslerInformation* q = (ZcmCameraBaslerInformation*) malloc(sizeof(ZcmCameraBaslerInformation));
    __ZcmCameraBaslerInformation_clone_array(p, q, 1);
    return q;
}

void ZcmCameraBaslerInformation_destroy(ZcmCameraBaslerInformation* p)
{
    __ZcmCameraBaslerInformation_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmCameraBaslerInformation_publish(zcm_t* zcm, const char* channel, const ZcmCameraBaslerInformation* p)
{
      uint32_t max_data_size = ZcmCameraBaslerInformation_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmCameraBaslerInformation_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmCameraBaslerInformation_subscription_t {
    ZcmCameraBaslerInformation_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmCameraBaslerInformation_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmCameraBaslerInformation p;
    memset(&p, 0, sizeof(ZcmCameraBaslerInformation));
    status = ZcmCameraBaslerInformation_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding ZcmCameraBaslerInformation!!!\n", status);
        #endif
        return;
    }

    ZcmCameraBaslerInformation_subscription_t* h = (ZcmCameraBaslerInformation_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmCameraBaslerInformation_decode_cleanup (&p);
}

ZcmCameraBaslerInformation_subscription_t* ZcmCameraBaslerInformation_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmCameraBaslerInformation_handler_t f, void* userdata)
{
    ZcmCameraBaslerInformation_subscription_t* n = (ZcmCameraBaslerInformation_subscription_t*)
                       malloc(sizeof(ZcmCameraBaslerInformation_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmCameraBaslerInformation_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg ZcmCameraBaslerInformation ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int ZcmCameraBaslerInformation_unsubscribe(zcm_t* zcm, ZcmCameraBaslerInformation_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe ZcmCameraBaslerInformation_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

