// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _ZcmCameraBaslerImagePresentation_h
#define _ZcmCameraBaslerImagePresentation_h

#ifdef __cplusplus
extern "C" {
#endif

/**
 * =======================================================================================
 * =======================================================================================
 * @struct ZcmCameraBaslerImagePresentation
 * @brief Картинка.
 *
 * @var ZcmCameraBaslerImagePresentation::width
 * @brief ширина.
 * @var ZcmCameraBaslerImagePresentation::height
 * @brief высота.
 * @var ZcmCameraBaslerImagePresentation::data
 * @brief данные картинки.
 *
 * @var ZcmCameraBaslerImagePresentation::bytes_per_line
 * @brief Часто линии картинок выравниваются, переменная указывает какой реальный
 * размер линии используется.
 *
 * @var ZcmCameraBaslerImagePresentation::format
 * @brief Формат задается строкой, но должен содержать фиксированные обозначения: \n
 * Gray_8, RGB_888, BGR_888.
 *
 */
typedef struct _ZcmCameraBaslerImagePresentation ZcmCameraBaslerImagePresentation;
struct _ZcmCameraBaslerImagePresentation
{
    int32_t    width;
    int32_t    height;
    int32_t    bytes_per_line;
    char*      format;
    int32_t    data_size;
    uint8_t    *data;
};

/**
 * Create a deep copy of a ZcmCameraBaslerImagePresentation.
 * When no longer needed, destroy it with ZcmCameraBaslerImagePresentation_destroy()
 */
ZcmCameraBaslerImagePresentation* ZcmCameraBaslerImagePresentation_copy(const ZcmCameraBaslerImagePresentation* to_copy);

/**
 * Destroy an instance of ZcmCameraBaslerImagePresentation created by ZcmCameraBaslerImagePresentation_copy()
 */
void ZcmCameraBaslerImagePresentation_destroy(ZcmCameraBaslerImagePresentation* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _ZcmCameraBaslerImagePresentation_subscription_t ZcmCameraBaslerImagePresentation_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * ZcmCameraBaslerImagePresentation is received.
 */
typedef void(*ZcmCameraBaslerImagePresentation_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const ZcmCameraBaslerImagePresentation* msg, void* userdata);

/**
 * Publish a message of type ZcmCameraBaslerImagePresentation using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int ZcmCameraBaslerImagePresentation_publish(zcm_t* zcm, const char* channel, const ZcmCameraBaslerImagePresentation* msg);

/**
 * Subscribe to messages of type ZcmCameraBaslerImagePresentation using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to ZcmCameraBaslerImagePresentation_unsubscribe.
 */
ZcmCameraBaslerImagePresentation_subscription_t* ZcmCameraBaslerImagePresentation_subscribe(zcm_t* zcm, const char* channel, ZcmCameraBaslerImagePresentation_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by ZcmCameraBaslerImagePresentation_subscribe()
 */
int ZcmCameraBaslerImagePresentation_unsubscribe(zcm_t* zcm, ZcmCameraBaslerImagePresentation_subscription_t* hid);
/**
 * Encode a message of type ZcmCameraBaslerImagePresentation into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to ZcmCameraBaslerImagePresentation_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int ZcmCameraBaslerImagePresentation_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCameraBaslerImagePresentation* p);

/**
 * Decode a message of type ZcmCameraBaslerImagePresentation from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with ZcmCameraBaslerImagePresentation_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int ZcmCameraBaslerImagePresentation_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCameraBaslerImagePresentation* msg);

/**
 * Release resources allocated by ZcmCameraBaslerImagePresentation_decode()
 * @return 0
 */
int ZcmCameraBaslerImagePresentation_decode_cleanup(ZcmCameraBaslerImagePresentation* p);

/**
 * Check how many bytes are required to encode a message of type ZcmCameraBaslerImagePresentation
 */
uint32_t ZcmCameraBaslerImagePresentation_encoded_size(const ZcmCameraBaslerImagePresentation* p);
uint32_t ZcmCameraBaslerImagePresentation_struct_size(void);
uint32_t ZcmCameraBaslerImagePresentation_num_fields(void);
int      ZcmCameraBaslerImagePresentation_get_field(const ZcmCameraBaslerImagePresentation* p, uint32_t i, zcm_field_t* f);
const zcm_type_info_t* ZcmCameraBaslerImagePresentation_get_type_info(void);

// ZCM support functions. Users should not call these
int64_t  __ZcmCameraBaslerImagePresentation_get_hash(void);
uint64_t __ZcmCameraBaslerImagePresentation_hash_recursive(const __zcm_hash_ptr* p);
int      __ZcmCameraBaslerImagePresentation_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCameraBaslerImagePresentation* p, uint32_t elements);
int      __ZcmCameraBaslerImagePresentation_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCameraBaslerImagePresentation* p, uint32_t elements);
int      __ZcmCameraBaslerImagePresentation_decode_array_cleanup(ZcmCameraBaslerImagePresentation* p, uint32_t elements);
uint32_t __ZcmCameraBaslerImagePresentation_encoded_array_size(const ZcmCameraBaslerImagePresentation* p, uint32_t elements);
uint32_t __ZcmCameraBaslerImagePresentation_clone_array(const ZcmCameraBaslerImagePresentation* p, ZcmCameraBaslerImagePresentation* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
