// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _ZcmCameraBaslerJpegFrame_h
#define _ZcmCameraBaslerJpegFrame_h

#ifdef __cplusplus
extern "C" {
#endif

#include "ZcmCameraBaslerInformation.h"
#include "ZcmService.h"
/**
 * =======================================================================================
 * @struct ZcmCameraBaslerJpegFrame
 * @brief Сжатый JPEG-ом кадр от камеры.
 * Обычно это каждый N-ый принятый кадр для долгосрочного хранения.
 *
 *
 * @var ZcmCameraBaslerJpegFrame::synchronized
 * @brief Флаг, подтверждающий попадание фрейма (с небольшой погрешностью) 
 * на "временную сетку".
 *
 * @var ZcmCameraBaslerJpegFrame::timestamp_ns
 * @brief Метка времени, установленная камерой. Если PTP не "прогрелся", будет в
 * районе 70-го года.
 *
 * @var ZcmCameraBaslerJpegFrame::jpeg
 * @brief Сжатые данные. Их можно, например, сохранять в файлы с расширением .jpeg.
 *
 */
typedef struct _ZcmCameraBaslerJpegFrame ZcmCameraBaslerJpegFrame;
struct _ZcmCameraBaslerJpegFrame
{
    ZcmCameraBaslerInformation info;
    int8_t     synchronized;
    int64_t    timestamp_ns;
    int32_t    jpeg_size;
    uint8_t    *jpeg;
    ZcmService service;
};

/**
 * Create a deep copy of a ZcmCameraBaslerJpegFrame.
 * When no longer needed, destroy it with ZcmCameraBaslerJpegFrame_destroy()
 */
ZcmCameraBaslerJpegFrame* ZcmCameraBaslerJpegFrame_copy(const ZcmCameraBaslerJpegFrame* to_copy);

/**
 * Destroy an instance of ZcmCameraBaslerJpegFrame created by ZcmCameraBaslerJpegFrame_copy()
 */
void ZcmCameraBaslerJpegFrame_destroy(ZcmCameraBaslerJpegFrame* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _ZcmCameraBaslerJpegFrame_subscription_t ZcmCameraBaslerJpegFrame_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * ZcmCameraBaslerJpegFrame is received.
 */
typedef void(*ZcmCameraBaslerJpegFrame_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const ZcmCameraBaslerJpegFrame* msg, void* userdata);

/**
 * Publish a message of type ZcmCameraBaslerJpegFrame using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int ZcmCameraBaslerJpegFrame_publish(zcm_t* zcm, const char* channel, const ZcmCameraBaslerJpegFrame* msg);

/**
 * Subscribe to messages of type ZcmCameraBaslerJpegFrame using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to ZcmCameraBaslerJpegFrame_unsubscribe.
 */
ZcmCameraBaslerJpegFrame_subscription_t* ZcmCameraBaslerJpegFrame_subscribe(zcm_t* zcm, const char* channel, ZcmCameraBaslerJpegFrame_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by ZcmCameraBaslerJpegFrame_subscribe()
 */
int ZcmCameraBaslerJpegFrame_unsubscribe(zcm_t* zcm, ZcmCameraBaslerJpegFrame_subscription_t* hid);
/**
 * Encode a message of type ZcmCameraBaslerJpegFrame into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to ZcmCameraBaslerJpegFrame_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int ZcmCameraBaslerJpegFrame_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCameraBaslerJpegFrame* p);

/**
 * Decode a message of type ZcmCameraBaslerJpegFrame from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with ZcmCameraBaslerJpegFrame_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int ZcmCameraBaslerJpegFrame_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCameraBaslerJpegFrame* msg);

/**
 * Release resources allocated by ZcmCameraBaslerJpegFrame_decode()
 * @return 0
 */
int ZcmCameraBaslerJpegFrame_decode_cleanup(ZcmCameraBaslerJpegFrame* p);

/**
 * Check how many bytes are required to encode a message of type ZcmCameraBaslerJpegFrame
 */
uint32_t ZcmCameraBaslerJpegFrame_encoded_size(const ZcmCameraBaslerJpegFrame* p);
uint32_t ZcmCameraBaslerJpegFrame_struct_size(void);
uint32_t ZcmCameraBaslerJpegFrame_num_fields(void);
int      ZcmCameraBaslerJpegFrame_get_field(const ZcmCameraBaslerJpegFrame* p, uint32_t i, zcm_field_t* f);
const zcm_type_info_t* ZcmCameraBaslerJpegFrame_get_type_info(void);

// ZCM support functions. Users should not call these
int64_t  __ZcmCameraBaslerJpegFrame_get_hash(void);
uint64_t __ZcmCameraBaslerJpegFrame_hash_recursive(const __zcm_hash_ptr* p);
int      __ZcmCameraBaslerJpegFrame_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCameraBaslerJpegFrame* p, uint32_t elements);
int      __ZcmCameraBaslerJpegFrame_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCameraBaslerJpegFrame* p, uint32_t elements);
int      __ZcmCameraBaslerJpegFrame_decode_array_cleanup(ZcmCameraBaslerJpegFrame* p, uint32_t elements);
uint32_t __ZcmCameraBaslerJpegFrame_encoded_array_size(const ZcmCameraBaslerJpegFrame* p, uint32_t elements);
uint32_t __ZcmCameraBaslerJpegFrame_clone_array(const ZcmCameraBaslerJpegFrame* p, ZcmCameraBaslerJpegFrame* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
